default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: papr_boi_development
  username: Martin

test:
  <<: *default
  database: papr_boi_test

production:
  <<: *default
  database: papr_boi_production
  username: papr_boi
  password: <%= ENV['PAPR_BOI_DATABASE_PASSWORD'] %>
